version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.20.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - DEFAULT_VECTORIZER_MODULE=none
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - ./weaviate_data:/var/lib/weaviate
